// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// iProjector_cpp
Rcpp::List iProjector_cpp(const arma::mat& G, const arma::vec& eta, const arma::vec& v, arma::uword maxit, double convTolerance);
RcppExport SEXP _boltzmannTest_iProjector_cpp(SEXP GSEXP, SEXP etaSEXP, SEXP vSEXP, SEXP maxitSEXP, SEXP convToleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type convTolerance(convToleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(iProjector_cpp(G, eta, v, maxit, convTolerance));
    return rcpp_result_gen;
END_RCPP
}
// matrix_hasFullRowRank_cpp
bool matrix_hasFullRowRank_cpp(const arma::mat& G, double tol);
RcppExport SEXP _boltzmannTest_matrix_hasFullRowRank_cpp(SEXP GSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_hasFullRowRank_cpp(G, tol));
    return rcpp_result_gen;
END_RCPP
}
// eta_isFeasible_cpp
bool eta_isFeasible_cpp(const arma::mat& G, const arma::vec& eta, double tol);
RcppExport SEXP _boltzmannTest_eta_isFeasible_cpp(SEXP GSEXP, SEXP etaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_isFeasible_cpp(G, eta, tol));
    return rcpp_result_gen;
END_RCPP
}
// startAndBars
arma::imat startAndBars(arma::uword N, arma::uword k);
RcppExport SEXP _boltzmannTest_startAndBars(SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(startAndBars(N, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boltzmannTest_iProjector_cpp", (DL_FUNC) &_boltzmannTest_iProjector_cpp, 5},
    {"_boltzmannTest_matrix_hasFullRowRank_cpp", (DL_FUNC) &_boltzmannTest_matrix_hasFullRowRank_cpp, 2},
    {"_boltzmannTest_eta_isFeasible_cpp", (DL_FUNC) &_boltzmannTest_eta_isFeasible_cpp, 3},
    {"_boltzmannTest_startAndBars", (DL_FUNC) &_boltzmannTest_startAndBars, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_boltzmannTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
