# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iProjector_cpp <- function(G, eta, v, maxit, convTolerance) {
    .Call(`_boltzmannTest_iProjector_cpp`, G, eta, v, maxit, convTolerance)
}

