# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iProjector_cpp <- function(G, eta, v, maxit, convTolerance) {
    .Call(`_boltzmannTest_iProjector_cpp`, G, eta, v, maxit, convTolerance)
}

multinomialPvalue_cpp <- function(G, eta, mu, v, N) {
    .Call(`_boltzmannTest_multinomialPvalue_cpp`, G, eta, mu, v, N)
}

multinomialPvalue_incremental_cpp <- function(G, eta, mu, v, N) {
    .Call(`_boltzmannTest_multinomialPvalue_incremental_cpp`, G, eta, mu, v, N)
}

matrix_hasFullRowRank_cpp <- function(G, tol) {
    .Call(`_boltzmannTest_matrix_hasFullRowRank_cpp`, G, tol)
}

eta_isFeasible_cpp <- function(G, eta, tol) {
    .Call(`_boltzmannTest_eta_isFeasible_cpp`, G, eta, tol)
}

startAndBars <- function(N, k) {
    .Call(`_boltzmannTest_startAndBars`, N, k)
}

which_approx_equal_cpp <- function(a, b, tol, reldiff = FALSE) {
    .Call(`_boltzmannTest_which_approx_equal_cpp`, a, b, tol, reldiff)
}

